export interface DamageTheme {
  icon: string;
  color: string;
  border: string;
  bg: string;
  vfx: string;
  glow: string;
  hex: string;
  parallax?: number;
}

export const DAMAGE_THEMES: Record<string, DamageTheme> = {
  fire: {
    icon: 'Flame',
    color: 'text-orange-500',
    border: 'border-orange-500/20',
    bg: 'bg-orange-500/5',
    vfx: 'vfx-dots',
    glow: 'shadow-orange-500/10',
    hex: '#f97316',
    parallax: -4,
  },
  cold: {
    icon: 'Snowflake',
    color: 'text-sky-300',
    border: 'border-sky-300/20',
    bg: 'bg-sky-300/5',
    vfx: 'vfx-grid',
    glow: 'shadow-sky-300/10',
    hex: '#7dd3fc',
    parallax: 4,
  },
  lightning: {
    icon: 'Zap',
    color: 'text-yellow-400',
    border: 'border-yellow-400/20',
    bg: 'bg-yellow-400/5',
    vfx: 'vfx-zigzag',
    glow: 'shadow-yellow-400/10',
    hex: '#facc15',
    parallax: -2,
  },
  acid: {
    icon: 'Droplet',
    color: 'text-lime-500',
    border: 'border-lime-500/20',
    bg: 'bg-lime-500/5',
    vfx: 'vfx-bubbles',
    glow: 'shadow-lime-500/10',
    hex: '#84cc16',
    parallax: 2,
  },
  poison: {
    icon: 'Skull',
    color: 'text-emerald-600',
    border: 'border-emerald-600/20',
    bg: 'bg-emerald-600/5',
    vfx: 'vfx-mist',
    glow: 'shadow-emerald-600/10',
    hex: '#059669',
    parallax: -3,
  },
  psychic: {
    icon: 'Brain',
    color: 'text-pink-500',
    border: 'border-pink-500/20',
    bg: 'bg-pink-500/5',
    vfx: 'vfx-waves',
    glow: 'shadow-pink-500/10',
    hex: '#ec4899',
    parallax: 5,
  },
  radiant: {
    icon: 'Sun',
    color: 'text-amber-200',
    border: 'border-amber-200/20',
    bg: 'bg-amber-200/5',
    vfx: 'vfx-beams',
    glow: 'shadow-amber-200/10',
    hex: '#fde68a',
    parallax: -5,
  },
  necrotic: {
    icon: 'Ghost',
    color: 'text-purple-900',
    border: 'border-purple-900/20',
    bg: 'bg-purple-900/5',
    vfx: 'vfx-decay',
    glow: 'shadow-purple-900/10',
    hex: '#581c87',
    parallax: 3,
  },
  force: {
    icon: 'Orbit',
    color: 'text-indigo-500',
    border: 'border-indigo-500/20',
    bg: 'bg-indigo-500/5',
    vfx: 'vfx-stars',
    glow: 'shadow-indigo-500/10',
    hex: '#6366f1',
    parallax: 0,
  },
  thunder: {
    icon: 'AudioLines',
    color: 'text-slate-400',
    border: 'border-slate-400/20',
    bg: 'bg-slate-400/5',
    vfx: 'vfx-concentric',
    glow: 'shadow-slate-400/10',
    hex: '#94a3b8',
    parallax: -1,
  },
  slashing: {
    icon: 'Sword',
    color: 'text-rose-700',
    border: 'border-rose-700/20',
    bg: 'bg-rose-700/5',
    vfx: 'vfx-lines-diag',
    glow: 'shadow-rose-700/10',
    hex: '#be123c',
    parallax: -2,
  },
  piercing: {
    icon: 'Target',
    color: 'text-red-800',
    border: 'border-red-800/20',
    bg: 'bg-red-800/5',
    vfx: 'vfx-dots-tight',
    glow: 'shadow-red-800/10',
    hex: '#991b1b',
    parallax: 1,
  },
  bludgeoning: {
    icon: 'Hammer',
    color: 'text-stone-500',
    border: 'border-stone-500/20',
    bg: 'bg-stone-500/5',
    vfx: 'vfx-cracks',
    glow: 'shadow-stone-500/10',
    hex: '#78716c',
    parallax: -1,
  },
};
