import { DAMAGE_TYPE_ICONS, SPELL_SCHOOL_ICONS, SPELL_UI_ICONS } from './spells';

export const MECHANIC_ICONS = {
  ritual: SPELL_UI_ICONS.Ritual,
  concentration: SPELL_UI_ICONS.Concentration,
  verbal: SPELL_UI_ICONS.Verbal,
  somatic: SPELL_UI_ICONS.Somatic,
  material: SPELL_UI_ICONS.Material,
  default: 'tied-scroll',
} as const;

export interface DamageTheme {
  icon: string;
  color: string;
  border: string;
  bg: string;
  vfx: string;
  glow: string;
  hex: string;
  distortion?: string;
  parallax?: number;
}

export const DAMAGE_THEMES: Record<string, DamageTheme> = {
  // Elemental / Damage Types
  fire: {
    icon: DAMAGE_TYPE_ICONS.fire,
    color: 'text-orange-500',
    border: 'border-orange-500/20',
    bg: 'bg-orange-500/5',
    vfx: 'vfx-dots',
    glow: 'shadow-orange-500/10',
    hex: '#f97316',
    parallax: -4,
  },
  cold: {
    icon: DAMAGE_TYPE_ICONS.cold,
    color: 'text-sky-300',
    border: 'border-sky-300/20',
    bg: 'bg-sky-300/5',
    vfx: 'vfx-grid',
    glow: 'shadow-sky-300/10',
    hex: '#7dd3fc',
    parallax: 4,
  },
  lightning: {
    icon: DAMAGE_TYPE_ICONS.lightning,
    color: 'text-yellow-400',
    border: 'border-yellow-400/20',
    bg: 'bg-yellow-400/5',
    vfx: 'vfx-zigzag',
    glow: 'shadow-yellow-400/10',
    hex: '#facc15',
    parallax: -2,
  },
  acid: {
    icon: DAMAGE_TYPE_ICONS.acid,
    color: 'text-lime-500',
    border: 'border-lime-500/20',
    bg: 'bg-lime-500/5',
    vfx: 'vfx-bubbles',
    glow: 'shadow-lime-500/10',
    hex: '#84cc16',
    parallax: 2,
  },
  poison: {
    icon: DAMAGE_TYPE_ICONS.poison,
    color: 'text-emerald-600',
    border: 'border-emerald-600/20',
    bg: 'bg-emerald-600/5',
    vfx: 'vfx-mist',
    glow: 'shadow-emerald-600/10',
    hex: '#059669',
    parallax: -3,
  },
  psychic: {
    icon: DAMAGE_TYPE_ICONS.psychic,
    color: 'text-pink-500',
    border: 'border-pink-500/20',
    bg: 'bg-pink-500/5',
    vfx: 'vfx-waves',
    glow: 'shadow-pink-500/10',
    hex: '#ec4899',
    parallax: 5,
  },
  radiant: {
    icon: DAMAGE_TYPE_ICONS.radiant,
    color: 'text-amber-200',
    border: 'border-amber-200/20',
    bg: 'bg-amber-200/5',
    vfx: 'vfx-beams',
    glow: 'shadow-amber-200/10',
    hex: '#fde68a',
    parallax: -5,
  },
  necrotic: {
    icon: DAMAGE_TYPE_ICONS.necrotic,
    color: 'text-purple-500',
    border: 'border-purple-500/20',
    bg: 'bg-purple-500/5',
    vfx: 'vfx-decay',
    glow: 'shadow-purple-500/10',
    hex: '#a855f7',
    parallax: 3,
  },
  force: {
    icon: DAMAGE_TYPE_ICONS.force,
    color: 'text-white',
    border: 'border-white/20',
    bg: 'bg-white/5',
    vfx: 'force-shockwave',
    glow: 'shadow-white/20',
    hex: '#ffffff',
    distortion: 'force-distortion-heavy opacity-0 group-hover:opacity-100',
    parallax: 0,
  },
  thunder: {
    icon: DAMAGE_TYPE_ICONS.thunder,
    color: 'text-slate-400',
    border: 'border-slate-400/20',
    bg: 'bg-slate-400/5',
    vfx: 'vfx-concentric',
    glow: 'shadow-slate-400/10',
    hex: '#94a3b8',
    distortion: 'vfx-sonic-distortion',
    parallax: -1,
  },
  slashing: {
    icon: DAMAGE_TYPE_ICONS.slashing,
    color: 'text-rose-700',
    border: 'border-rose-700/20',
    bg: 'bg-rose-700/5',
    vfx: 'vfx-lines-diag',
    glow: 'shadow-rose-700/10',
    hex: '#be123c',
    parallax: -2,
  },
  piercing: {
    icon: DAMAGE_TYPE_ICONS.piercing,
    color: 'text-red-800',
    border: 'border-red-800/20',
    bg: 'bg-red-800/5',
    vfx: 'vfx-dots-tight',
    glow: 'shadow-red-800/10',
    hex: '#991b1b',
    parallax: 1,
  },
  bludgeoning: {
    icon: DAMAGE_TYPE_ICONS.bludgeoning,
    color: 'text-stone-500',
    border: 'border-stone-500/20',
    bg: 'bg-stone-500/5',
    vfx: 'vfx-cracks',
    glow: 'shadow-stone-500/10',
    hex: '#78716c',
    parallax: -1,
  },
};

export const CATEGORY_THEMES: Record<string, DamageTheme> = {
  // Functional / Category
  buff: {
    icon: 'armor-upgrade',
    color: 'text-emerald-400',
    border: 'border-emerald-400/20',
    bg: 'bg-emerald-400/5',
    vfx: 'vfx-grid',
    glow: 'shadow-emerald-400/10',
    hex: '#34d399',
    parallax: 0,
  },
  utility: {
    icon: 'convergence-target',
    color: 'text-amber-400',
    border: 'border-amber-400/20',
    bg: 'bg-amber-400/5',
    vfx: 'vfx-dots',
    glow: 'shadow-amber-400/10',
    hex: '#fbbf24',
    parallax: 0,
  },
  control: {
    icon: 'despair',
    color: 'text-yellow-500',
    border: 'border-yellow-500/20',
    bg: 'bg-yellow-500/5',
    vfx: 'vfx-ethereal',
    glow: 'shadow-yellow-500/10',
    hex: '#eab308',
    parallax: 0,
  },
};

export const SCHOOL_THEMES: Record<string, DamageTheme> = {
  // Traditional / Schools
  abjuration: {
    icon: SPELL_SCHOOL_ICONS.abjuration,
    color: 'text-blue-400',
    border: 'border-blue-400/20',
    bg: 'bg-blue-400/5',
    vfx: 'vfx-grid',
    glow: 'shadow-blue-400/10',
    hex: '#60a5fa',
    parallax: 0,
  },
  conjuration: {
    icon: SPELL_SCHOOL_ICONS.conjuration,
    color: 'text-yellow-400',
    border: 'border-yellow-400/20',
    bg: 'bg-yellow-400/5',
    vfx: 'vfx-dots-tight',
    glow: 'shadow-yellow-400/10',
    hex: '#facc15',
    parallax: 0,
  },
  divination: {
    icon: SPELL_SCHOOL_ICONS.divination,
    color: 'text-emerald-400',
    border: 'border-emerald-400/20',
    bg: 'bg-emerald-400/5',
    vfx: 'vfx-waves',
    glow: 'shadow-emerald-400/10',
    hex: '#34d399',
    parallax: 0,
  },
  enchantment: {
    icon: SPELL_SCHOOL_ICONS.enchantment,
    color: 'text-pink-400',
    border: 'border-pink-400/20',
    bg: 'bg-pink-400/5',
    vfx: 'vfx-ethereal',
    glow: 'shadow-pink-400/10',
    hex: '#f472b6',
    parallax: 0,
  },
  evocation: {
    icon: SPELL_SCHOOL_ICONS.evocation,
    color: 'text-orange-500',
    border: 'border-orange-500/20',
    bg: 'bg-orange-500/5',
    vfx: 'vfx-dots',
    glow: 'shadow-orange-500/10',
    hex: '#f97316',
    parallax: 0,
  },
  illusion: {
    icon: SPELL_SCHOOL_ICONS.illusion,
    color: 'text-purple-400',
    border: 'border-purple-400/20',
    bg: 'bg-purple-400/5',
    vfx: 'vfx-mist',
    glow: 'shadow-purple-400/10',
    hex: '#a78bfa',
    parallax: 0,
  },
  necromancy: {
    icon: SPELL_SCHOOL_ICONS.necromancy,
    color: 'text-purple-600',
    border: 'border-purple-600/20',
    bg: 'bg-purple-600/5',
    vfx: 'vfx-decay',
    glow: 'shadow-purple-600/10',
    hex: '#9333ea',
    parallax: 0,
  },
  transmutation: {
    icon: SPELL_SCHOOL_ICONS.transmutation,
    color: 'text-amber-600',
    border: 'border-amber-600/20',
    bg: 'bg-amber-600/5',
    vfx: 'vfx-cracks',
    glow: 'shadow-amber-600/10',
    hex: '#d97706',
    parallax: 0,
  },
};

export const DEFAULT_THEME: DamageTheme = {
  icon: 'tied-scroll',
  color: 'text-slate-400',
  border: 'border-slate-400/20',
  bg: 'bg-slate-400/5',
  vfx: 'vfx-dots',
  glow: 'shadow-slate-400/10',
  hex: '#94a3b8',
  parallax: 0,
};
